### PR TITLE
Ac404 17 adding merchants

### PR DESCRIPTION
**Pull request by mkljaic20**
Made changes to use text input and button presets.

### CODE REVIEW

**Review by aantonic20 — DISMISSED** [review]
Everything looks well written and organized.

**Review by timjuic — CHANGES_REQUESTED** [review]
Its nice that you switched to using our paypro components. But there are still inconsistencies in the design.

- Merchant name page should be using the PayProHeading, which has already predefined font and styling as other parts of the app. Title should be aligned with input field. Buttons aligned to the right
Screenshot 2024-01-03 at 12 24 09

- Business address page should have reasonably distanced input fields. And using PayProHeading
Screenshot 2024-01-03 at 12 27 40

- Cards page is looking great. But buttons are not visible if there are more cards added. I suggest to move them to some kind of dropdown menu.
Screenshot 2024-01-03 at 12 29 05

**Review by jivancic20 — DISMISSED** [review]
Looks good

**Review by dominikn1 — APPROVED** [review]
Looks good.

**Review by timjuic — APPROVED** [review]

**Pull request merged**
