### PR TITLE
Ac404 132 auth refactor

### PR DESCRIPTION
**Pull request by timjuic**
This branch includes following:

- Significant recode of the auth module. 
- Refactored email login functionality in a separate module to prove modularity. Adjusted the implementation so it follow SOLID principles.
- Dynamically loading buttons from each auth module to the welcome page
- Removed old "hardcoded" buttons from welcome page
- Create AppConfig in core module. It holds the IP of the backend. Can be used as `AppConfig.BASE_URL`. This way we will avoid exposing the ip in the actual code

### CODE REVIEW

**Review by aantonic20 — DISMISSED** [review]
Everything looks good and works as intended. Good work on refactoring the auth modules and making the app more modular!

**Review by jivancic20 — DISMISSED** [review]
Good job on the refactoring!

**Review by mkljaic20 — DISMISSED** [review]

**Comment by timjuic** [comment]
Changes from this branch were already carried over to develop with #29  branch

**Comment by timjuic** [comment]
Changes from this branch were already carried over to develop with #29  branch

**Review by dominikn1 — APPROVED** [review]

**Review by aantonic20 — APPROVED** [review]
Looks good.

**Review by mkljaic20 — APPROVED** [review]

**Pull request merged**
